const categories=[['🍔','طعام ومطاعم'],['🛒','بقالة وسوبرماركت'],['👕','ملابس وأحذية'],['🏠','عقارات'],['🚗','سيارات'],['📱','إلكترونيات'],['🔧','أدوات وصيانة'],['💊','صيدليات'],['💐','ورد وهدايا'],['🛋️','أثاث وديكور'],['💇','صالونات'],['🧹','خدمات منزلية'],['🚚','نقل وتوصيل'],['🏨','فنادق'],['🎟️','تذاكر وفعاليات'],['📚','كتب وقرطاسية'],['🐶','حيوانات أليفة'],['👶','أطفال'],['⚽','رياضة'],['🎮','ألعاب'],['🛠️','معدات'],['💎','مجوهرات'],['🧴','تجميل وعناية'],['☕','مقاهي'],['🥖','مخابز'],['🍰','حلويات']];
const stores=[
 {id:1,icon:'🍕',name:'بيتزا نابولي',cat:'طعام ومطاعم',meta:'⭐ 4.8 · 20-30 دقيقة',tag:'توصيل مجاني',products:[['بيتزا مارغريتا','7.50 €'],['بيتزا خضار','8.50 €'],['بيتزا بيبروني','9.50 €']]},
 {id:2,icon:'🛒',name:'ماركت المدينة',cat:'بقالة وسوبرماركت',meta:'⭐ 4.6 · 15-25 دقيقة',tag:'أسعار يومية',products:[['سلة خضار طازجة','12 €'],['مياه 6 × 1.5L','4.20 €'],['حليب كامل الدسم','1.60 €']]},
 {id:3,icon:'💻',name:'تك زون',cat:'إلكترونيات',meta:'⭐ 4.9 · استلام اليوم',tag:'ضمان سنة',products:[['لابتوب Pro 15','799 €'],['سماعات لاسلكية','49 €'],['شاحن سريع USB-C','19 €']]},
 {id:4,icon:'👟',name:'ستايل ستور',cat:'ملابس وأحذية',meta:'⭐ 4.7 · توصيل 1-2 يوم',tag:'إرجاع مجاني',products:[['حذاء رياضي','65 €'],['هودي قطن','39 €'],['تيشيرت أساسي','19 €']]},
 {id:5,icon:'💊',name:'صيدلية الشفاء',cat:'صيدليات',meta:'⭐ 4.9 · 20-35 دقيقة',tag:'صيدلي متاح',products:[['مستلزمات عناية','12 €'],['فيتامينات','15 €'],['عناية بالبشرة','18 €']]},
 {id:6,icon:'🏠',name:'بيوتي للعقارات',cat:'عقارات',meta:'⭐ 4.6 · 124 إعلان',tag:'بيع وإيجار',products:[['شقة غرفتين للإيجار','850 € / شهر'],['شقة 3 غرف','1,150 € / شهر'],['استوديو مفروش','690 € / شهر']]},
 {id:7,icon:'🚗',name:'أوتو ماركت',cat:'سيارات',meta:'⭐ 4.5 · 86 سيارة',tag:'سيارات مستعملة',products:[['Toyota Corolla 2022','18,900 €'],['VW Golf 2021','16,500 €'],['Kia Sportage 2023','24,900 €']]},
 {id:8,icon:'☕',name:'مزاج كافيه',cat:'مقاهي',meta:'⭐ 4.8 · 10-20 دقيقة',tag:'الأكثر طلباً',products:[['لاتيه','3.50 €'],['كابتشينو','3.20 €'],['كيكة شوكولا','4.50 €']]}
];
let cart=JSON.parse(localStorage.getItem('storey_cart')||'[]');
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function renderCategories(){ $('#categoryGrid').innerHTML=categories.map((c,i)=>`<button class="category" data-cat="${c[1]}"><span class="icon">${c[0]}</span><span>${c[1]}</span></button>`).join(''); $$('.category').forEach(b=>b.onclick=()=>search(b.dataset.cat)); }
function card(s){return `<article class="store-card" data-store="${s.id}"><div class="store-image">${s.icon}</div><div class="store-info"><h3>${s.name}</h3><div class="store-meta"><span>${s.meta}</span></div><span class="tag">${s.tag}</span></div></article>`}
function renderStores(list=stores){$('#storeGrid').innerHTML=list.map(card).join(''); bindCards($('#storeGrid'));}
function bindCards(root=document){root.querySelectorAll('[data-store]').forEach(c=>c.onclick=()=>openStore(+c.dataset.store));}
function search(q){q=q.trim(); if(!q){$('#resultsSection').hidden=true;return} const terms=q.toLowerCase();const list=stores.filter(s=>(s.name+' '+s.cat+' '+s.tag+' '+s.products.flat().join(' ')).toLowerCase().includes(terms));$('#resultsTitle').textContent=list.length?`نتائج «${q}»`:`ما لقينا نتائج لـ «${q}»`;$('#resultsGrid').innerHTML=list.length?list.map(card).join(''):`<div class="store-card" style="grid-column:1/-1;padding:35px;text-align:center">جرّب كلمة ثانية أو اختر فئة من الفئات فوق.</div>`;$('#resultsSection').hidden=false;bindCards($('#resultsGrid'));$('#resultsSection').scrollIntoView({behavior:'smooth',block:'start'})}
function openStore(id){const s=stores.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="store-modal-head"><div class="big-icon">${s.icon}</div><div><h2>${s.name}</h2><div class="muted">${s.cat} · ${s.meta}</div></div></div><div>${s.products.map((p,i)=>`<div class="product"><div><strong>${p[0]}</strong><small>${p[1]}</small></div><button data-add="${id}" data-index="${i}">+ أضف</button></div>`).join('')}</div>`;showModal();$$('[data-add]').forEach(b=>b.onclick=()=>{const p=s.products[+b.dataset.index];cart.push({store:s.name,name:p[0],price:p[1]});saveCart();toast(`تمت إضافة ${p[0]} للسلة`)});}
function saveCart(){localStorage.setItem('storey_cart',JSON.stringify(cart));$('#cartCount').textContent=cart.length}
function showModal(){ $('#modal').hidden=false;document.body.style.overflow='hidden'}function closeModal(){$('#modal').hidden=true;document.body.style.overflow=''}
function auth(){let mode='login';function draw(){ $('#modalContent').innerHTML=`<h2>${mode==='login'?'أهلاً بعودتك 👋':'إنشاء حساب جديد ✨'}</h2><p class="muted">${mode==='login'?'سجّل دخولك لتتابع طلباتك ومحلاتك المفضلة.':'أنشئ حسابك وابدأ الطلب بسهولة.'}</p><div class="auth-tabs"><button class="${mode==='login'?'active':''}" id="loginTab">تسجيل الدخول</button><button class="${mode==='signup'?'active':''}" id="signupTab">إنشاء حساب</button></div>${mode==='signup'?'<div class="field"><label>الاسم</label><input id="authName" placeholder="اسمك الكامل"></div>':''}<div class="field"><label>البريد الإلكتروني</label><input id="authEmail" type="email" placeholder="name@example.com"></div><div class="field"><label>كلمة المرور</label><input id="authPass" type="password" placeholder="••••••••"></div><button class="primary" id="authSubmit">${mode==='login'?'دخول':'إنشاء الحساب'}</button><button class="guest" id="guest">الدخول كزائر</button>`;$('#loginTab').onclick=()=>{mode='login';draw()};$('#signupTab').onclick=()=>{mode='signup';draw()};$('#guest').onclick=()=>{localStorage.setItem('storey_user',JSON.stringify({guest:true,name:'زائر'}));closeModal();updateAccount();toast('أهلاً فيك! دخلت كزائر 👋')};$('#authSubmit').onclick=()=>{const email=$('#authEmail').value.trim(),pass=$('#authPass').value;if(!email||!pass||(mode==='signup'&&!$('#authName').value.trim()))return toast('عبّي المعلومات المطلوبة أولاً');localStorage.setItem('storey_user',JSON.stringify({guest:false,name:mode==='signup'?$('#authName').value.trim():email.split('@')[0],email}));closeModal();updateAccount();toast(mode==='login'?'تم تسجيل الدخول بنجاح':'تم إنشاء حسابك بنجاح 🎉')};}showModal();draw()}
function updateAccount(){const u=JSON.parse(localStorage.getItem('storey_user')||'null');$('#accountBtn').textContent=u?`حسابي · ${u.name}`:'دخول / حساب جديد'}
function cartModal(){const total=cart.length;$('#modalContent').innerHTML=`<h2>سلة الطلب 🛒</h2><p class="muted">${total?`عندك ${total} ${total===1?'عنصر':'عناصر'} بالسلة.`:'السلة فاضية حالياً.'}</p>${cart.map((x,i)=>`<div class="product"><div><strong>${x.name}</strong><small>${x.store} · ${x.price}</small></div><button data-remove="${i}">حذف</button></div>`).join('')}${total?'<button class="primary" id="checkout">متابعة لإتمام الطلب</button>':''}`;showModal();$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);saveCart();cartModal()});if($('#checkout'))$('#checkout').onclick=()=>toast('واجهة الدفع جاهزة للربط ببوابة الدفع لاحقاً')}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function resetHome(){window.scrollTo({top:0,behavior:'smooth'});$('#resultsSection').hidden=true;$('#searchInput').value=''}
$('#searchBtn').onclick=()=>search($('#searchInput').value);$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')search(e.target.value)});$$('[data-search]').forEach(b=>b.onclick=()=>{ $('#searchInput').value=b.dataset.search;search(b.dataset.search)});$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='home')resetHome();if(a==='account')auth();if(a==='cart')cartModal();if(a==='close')closeModal();if(a==='stores')document.querySelector('.stores-section').scrollIntoView({behavior:'smooth'});if(a==='categories')document.querySelector('.categories-section').scrollIntoView({behavior:'smooth'});if(a==='location')toast('حدد موقعك من المتصفح عند تفعيل الخرائط');if(a==='addStore')toast('نموذج إضافة النشاط سيكون متاحاً في لوحة أصحاب الأعمال');if(a==='help')toast('المساعدة: تواصل معنا من لوحة الدعم');if(a==='privacy')toast('خصوصيتك مهمة — البيانات التجريبية محفوظة على جهازك')});$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});renderCategories();renderStores();saveCart();updateAccount();
