const categories=[['🍔','طعام ومطاعم'],['🛒','بقالة وسوبرماركت'],['👕','ملابس وأحذية'],['🏠','عقارات'],['🚗','سيارات'],['📱','إلكترونيات'],['🔧','أدوات وصيانة'],['💊','صيدليات'],['💐','ورد وهدايا'],['🛋️','أثاث وديكور'],['💇','صالونات'],['🧹','خدمات منزلية'],['🚚','نقل وتوصيل'],['🏨','فنادق'],['🎟️','تذاكر وفعاليات'],['📚','كتب وقرطاسية'],['🐶','حيوانات أليفة'],['👶','أطفال'],['⚽','رياضة'],['🎮','ألعاب'],['🛠️','معدات'],['💎','مجوهرات'],['🧴','تجميل وعناية'],['☕','مقاهي'],['🥖','مخابز'],['🍰','حلويات']];
const stores=[{id:1,icon:'🍕',name:'بيتزا نابولي',cat:'طعام ومطاعم',meta:'⭐ 4.8 · 20-30 دقيقة',tag:'توصيل مجاني',products:[['بيتزا مارغريتا','7.50 €'],['بيتزا خضار','8.50 €'],['بيتزا بيبروني','9.50 €']]},{id:2,icon:'🛒',name:'ماركت المدينة',cat:'بقالة وسوبرماركت',meta:'⭐ 4.6 · 15-25 دقيقة',tag:'أسعار يومية',products:[['سلة خضار طازجة','12 €'],['مياه 6 × 1.5L','4.20 €'],['حليب كامل الدسم','1.60 €']]},{id:3,icon:'💻',name:'تك زون',cat:'إلكترونيات',meta:'⭐ 4.9 · استلام اليوم',tag:'ضمان سنة',products:[['لابتوب Pro 15','799 €'],['سماعات لاسلكية','49 €'],['شاحن سريع USB-C','19 €']]},{id:4,icon:'👟',name:'ستايل ستور',cat:'ملابس وأحذية',meta:'⭐ 4.7 · توصيل 1-2 يوم',tag:'إرجاع مجاني',products:[['حذاء رياضي','65 €'],['هودي قطن','39 €'],['تيشيرت أساسي','19 €']]},{id:5,icon:'💊',name:'صيدلية الشفاء',cat:'صيدليات',meta:'⭐ 4.9 · 20-35 دقيقة',tag:'صيدلي متاح',products:[['مستلزمات عناية','12 €'],['فيتامينات','15 €'],['عناية بالبشرة','18 €']]},{id:6,icon:'🏠',name:'بيوتي للعقارات',cat:'عقارات',meta:'⭐ 4.6 · 124 إعلان',tag:'بيع وإيجار',products:[['شقة غرفتين للإيجار','850 € / شهر'],['شقة 3 غرف','1,150 € / شهر'],['استوديو مفروش','690 € / شهر']]},{id:7,icon:'🚗',name:'أوتو ماركت',cat:'سيارات',meta:'⭐ 4.5 · 86 سيارة',tag:'سيارات مستعملة',products:[['Toyota Corolla 2022','18,900 €'],['VW Golf 2021','16,500 €'],['Kia Sportage 2023','24,900 €']]},{id:8,icon:'☕',name:'مزاج كافيه',cat:'مقاهي',meta:'⭐ 4.8 · 10-20 دقيقة',tag:'الأكثر طلباً',products:[['لاتيه','3.50 €'],['كابتشينو','3.20 €'],['كيكة شوكولا','4.50 €']]}];
const ADMIN_WHATSAPP='YOUR_WHATSAPP_NUMBER';
let cart=JSON.parse(localStorage.getItem('storey_cart')||'[]'),adminUser=null,adminProfile=null;
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),db=()=>window.supabaseClient;
function renderCategories(){$('#categoryGrid').innerHTML=categories.map(c=>`<button class="category" data-cat="${c[1]}"><span class="icon">${c[0]}</span><span>${c[1]}</span></button>`).join('');$$('.category').forEach(b=>b.onclick=()=>search(b.dataset.cat))}
function card(s){return `<article class="store-card" data-store="${s.id}"><div class="store-image">${s.icon}</div><div class="store-info"><h3>${s.name}</h3><div class="store-meta">${s.meta}</div><span class="tag">${s.tag}</span></div></article>`}
function renderStores(list=stores){$('#storeGrid').innerHTML=list.map(card).join('');bindCards($('#storeGrid'))}
function bindCards(root=document){root.querySelectorAll('[data-store]').forEach(c=>c.onclick=()=>openStore(+c.dataset.store))}
function localReply(q,list){const n=q.toLowerCase();if(n.includes('بيتزا')||n.includes('أكل')||n.includes('مطعم'))return `يا سلام 😄 واضح إن المعدة هي صاحبة القرار اليوم. لقيت لك خيارات طعام، شوف اللي بناسبك واضغط عليه.`;if(n.includes('شقة')||n.includes('بيت')||n.includes('عقار'))return `خلينا ندور بعقلية سمسار شاطر 😄 لقيت لك نتائج العقارات الموجودة حالياً بالمنصة.`;if(n.includes('هاتف')||n.includes('موبايل')||n.includes('لابتوب'))return `تمام يا خبير التقنية 😎 فتشت بين الإلكترونيات وطلعت لك الخيارات الموجودة حالياً.`;if(n.includes('ملابس')||n.includes('حذاء'))return `بدنا نطلعك شي مرتب بدون وجع راس 😄 هاي الخيارات اللي لقيتها.`;if(n.includes('صيدلية'))return `ولا يهمك 💊 لقيت لك الصيدلية المتاحة ضمن بيانات المنصة.`;return list.length?`تمام، فهمت عليك تقريباً 😄 فتشت بالمتاجر والمنتجات الموجودة وطلعت لك أقرب اقتراحات لبحثك.`:`مممم 🤔 دورت بالموجود عندي حالياً وما لقيت تطابق واضح. جرّب اسم فئة أو منتج ثاني.`}
function search(q){q=q.trim();if(!q)return $('#resultsSection').hidden=true;const sec=$('#resultsSection'),thinking=$('#thinking'),grid=$('#resultsGrid');sec.hidden=false;$('#resultsTitle').textContent=`بحث عن «${q}»`;$('#aiResultCard').style.display='none';thinking.hidden=false;grid.innerHTML='';sec.scrollIntoView({behavior:'smooth'});setTimeout(()=>{const list=stores.filter(s=>(s.name+' '+s.cat+' '+s.tag+' '+s.products.flat().join(' ')).toLowerCase().includes(q.toLowerCase()));thinking.hidden=true;$('#aiResultCard').style.display='block';$('#aiResultText').textContent=localReply(q,list);grid.innerHTML=list.length?list.map(card).join(''):`<div class="store-card" style="grid-column:1/-1;padding:35px;text-align:center"><strong>ما لقيت نتيجة مطابقة حالياً</strong><br><span class="muted">جرّب كلمة ثانية أو اختار فئة من فوق.</span></div>`;bindCards(grid)},700)}
function openStore(id){const s=stores.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="store-modal-head"><div class="big-icon">${s.icon}</div><div><h2>${s.name}</h2><div class="muted">${s.cat} · ${s.meta}</div></div></div>${s.products.map((p,i)=>`<div class="product"><div><strong>${p[0]}</strong><small>${p[1]}</small></div><button data-add="${i}">+ أضف</button></div>`).join('')}<button class="primary" id="quickWa">طلب عبر WhatsApp</button>`;showModal();$$('[data-add]').forEach(b=>b.onclick=()=>{const p=s.products[+b.dataset.add];cart.push({store:s.name,name:p[0],price:p[1]});saveCart();toast('تمت الإضافة للسلة ✅')});$('#quickWa').onclick=()=>whatsappOrder([{store:s.name,name:'طلب عبر المتجر',price:''}],s.name)}
function saveCart(){localStorage.setItem('storey_cart',JSON.stringify(cart));$('#cartCount').textContent=cart.length}
function showModal(){ $('#modal').hidden=false;document.body.style.overflow='hidden'}function closeModal(){$('#modal').hidden=true;document.body.style.overflow=''}
function cartModal(){const total=cart.length;$('#modalContent').innerHTML=`<h2>سلة الطلب 🛒</h2><p class="muted">${total?`عندك ${total} عناصر.`:'السلة فاضية حالياً.'}</p>${cart.map((x,i)=>`<div class="product"><div><strong>${x.name}</strong><small>${x.store} · ${x.price}</small></div><button data-r="${i}">حذف</button></div>`).join('')}${total?'<button class="primary" id="checkout">إرسال الطلب عبر WhatsApp</button>':''}`;showModal();$$('[data-r]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.r,1);saveCart();cartModal()});if($('#checkout'))$('#checkout').onclick=()=>whatsappOrder(cart,cart[0]?.store)}
function whatsappOrder(items,store){if(ADMIN_WHATSAPP==='YOUR_WHATSAPP_NUMBER'){toast('أضف رقم WhatsApp للإدارة في app.js أولاً');return}const msg=`طلب جديد من ستورِي 🛍️\n\nالمتجر: ${store||'غير محدد'}\n${items.map(x=>`• ${x.name}${x.price?' — '+x.price:''}`).join('\n')}\n\nيرجى تأكيد الطلب.`;window.open(`https://wa.me/${ADMIN_WHATSAPP.replace(/\D/g,'')}?text=${encodeURIComponent(msg)}`,'_blank')}
function addStoreRequest(){const fields=[['اسم المتجر *','srn'],['نوع النشاط','src'],['اسم صاحب المتجر','sro'],['رقم الهاتف','srp'],['WhatsApp للطلبات','srw'],['العنوان','sra'],['وصف المتجر','srd']];$('#modalContent').innerHTML=`<h2>أضف متجرك 🏪</h2><p class="muted">ما في داعي لتسجيل حساب. عبّي البيانات ورح تنرسل مباشرة إلى WhatsApp الإدارة.</p>${fields.map(x=>`<div class="field"><label>${x[0]}</label><input id="${x[1]}"></div>`).join('')}<button class="primary" id="sendSr">إرسال الطلب عبر WhatsApp</button>`;showModal();$('#sendSr').onclick=()=>{if(!$('#srn').value.trim())return toast('اكتب اسم المتجر');const msg=`طلب إضافة متجر جديد 🏪\n\nاسم المتجر: ${$('#srn').value}\nالنشاط: ${$('#src').value}\nصاحب المتجر: ${$('#sro').value}\nالهاتف: ${$('#srp').value}\nWhatsApp: ${$('#srw').value}\nالعنوان: ${$('#sra').value}\nالوصف: ${$('#srd').value}`;if(ADMIN_WHATSAPP==='YOUR_WHATSAPP_NUMBER')return toast('أضف رقم WhatsApp الإدارة في app.js');window.open(`https://wa.me/${ADMIN_WHATSAPP.replace(/\D/g,'')}?text=${encodeURIComponent(msg)}`,'_blank');closeModal()}}
function adminLogin(){let mode='login';const draw=()=>{$('#modalContent').innerHTML=`<h2>دخول الإدارة 🔒</h2><p class="muted">هذا الدخول مخصص لك كمدير المنصة فقط.</p><div class="field"><label>البريد الإلكتروني</label><input id="adminEmail" type="email" autocomplete="username"></div><div class="field"><label>كلمة المرور</label><input id="adminPass" type="password" autocomplete="current-password"></div><button class="primary" id="adminEnter">دخول لوحة الإدارة</button>`;showModal();$('#adminEnter').onclick=async()=>{const email=$('#adminEmail').value.trim(),password=$('#adminPass').value;if(!email||!password)return toast('اكتب البريد وكلمة المرور');const r=await db().auth.signInWithPassword({email,password});if(r.error)return toast('بيانات الإدارة غير صحيحة');const p=await db().from('profiles').select('*').eq('id',r.data.user.id).maybeSingle();if(p.data?.role!=='admin'){await db().auth.signOut();return toast('هذا الحساب ليس مديراً');}adminUser=r.data.user;adminProfile=p.data;closeModal();adminPanel()};};draw()}
async function adminPanel(){if(!adminUser||adminProfile?.role!=='admin')return adminLogin();const {data,error}=await db().from('store_requests').select('*').order('created_at',{ascending:false});if(error)return toast(error.message);$('#modalContent').innerHTML=`<h2>لوحة الإدارة 🔔</h2><p class="muted">طلبات المتاجر الواردة عبر النظام.</p>${data?.length?data.map(r=>`<div class="product"><div><strong>${r.store_name}</strong><small>${r.category||''} · ${r.owner_name||''}<br>${r.whatsapp||r.phone||''}<br>الحالة: ${r.status}</small></div><span class="tag">${r.status}</span></div>`).join(''):'<p class="muted">لا توجد طلبات مسجلة حالياً.</p>'}<button class="primary" id="adminLogout">تسجيل خروج الإدارة</button>`;showModal();$('#adminLogout').onclick=async()=>{await db().auth.signOut();adminUser=null;adminProfile=null;closeModal();toast('تم تسجيل خروج الإدارة')};}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}
function resetHome(){window.scrollTo({top:0,behavior:'smooth'});$('#resultsSection').hidden=true;$('#searchInput').value=''}
$('#searchBtn').onclick=()=>search($('#searchInput').value);$('#searchInput').onkeydown=e=>{if(e.key==='Enter')search(e.target.value)};$$('[data-search]').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.search;search(b.dataset.search)});
$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='home')resetHome();if(a==='admin')adminLogin();if(a==='cart')cartModal();if(a==='close')closeModal();if(a==='stores')document.querySelector('.stores-section').scrollIntoView({behavior:'smooth'});if(a==='categories')document.querySelector('.categories-section').scrollIntoView({behavior:'smooth'});if(a==='location')toast('الخريطة بالمرحلة التالية 🗺️');if(a==='addStore')addStoreRequest();if(a==='help')toast('المساعدة قريباً')});
$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};renderCategories();renderStores();saveCart();
