(() => {
  const mapStyle={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]};
  let map=null,userMarker=null,storeMarkers=[],selected=null;
  const $=s=>document.querySelector(s);const safe=t=>typeof window.toast==='function'?window.toast(t):alert(t);
  function openLocationPicker(){
    $('#modalContent').innerHTML=`<div class="location-modal"><div class="location-head"><div><span class="mini-label">التوصيل</span><h2>حدد موقع التوصيل 📍</h2></div><button class="location-use" id="useMyLocation">⌖ استخدم موقعي</button></div><p class="muted">اسمح بالموقع لنحدد مكانك بدقة، أو اضغط على الخريطة وحدد النقطة يدوياً.</p><div id="deliveryMap" class="delivery-map"></div><div class="location-coords" id="locationCoords">لم يتم تحديد الموقع بعد</div><button class="primary" id="confirmLocation" disabled>تأكيد موقع التوصيل</button></div>`;
    if(typeof showModal==='function')showModal();setTimeout(initMap,0);$('#useMyLocation').onclick=requestLocation;$('#confirmLocation').onclick=confirmLocation;
  }
  function initMap(){if(!window.maplibregl)return safe('تعذر تحميل الخريطة حالياً.');map=new maplibregl.Map({container:'deliveryMap',style:mapStyle,center:[35.9,33.5],zoom:5,attributionControl:true});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-left');map.on('load',loadStores);map.on('click',e=>selectLocation(e.lngLat.lat,e.lngLat.lng));requestLocation();}
  function requestLocation(){if(!navigator.geolocation)return safe('جهازك لا يدعم تحديد الموقع.');navigator.geolocation.getCurrentPosition(pos=>{const {latitude,longitude}=pos.coords;selectLocation(latitude,longitude,true);if(map)map.flyTo({center:[longitude,latitude],zoom:14,essential:true});},()=>safe('لم نتمكن من الوصول إلى موقعك. يمكنك تحديده يدوياً.'),{enableHighAccuracy:true,timeout:10000,maximumAge:30000});}
  function selectLocation(lat,lng,gps=false){selected={latitude:+lat,longitude:+lng,source:gps?'gps':'map',selected_at:new Date().toISOString()};if(userMarker)userMarker.remove();userMarker=new maplibregl.Marker({color:'#0a7b47'}).setLngLat([lng,lat]).addTo(map);$('#locationCoords').textContent=`📍 ${(+lat).toFixed(5)}, ${(+lng).toFixed(5)}`;$('#confirmLocation').disabled=false;}
  function confirmLocation(){if(!selected)return;localStorage.setItem('delivery_location',JSON.stringify(selected));const label=$('#locationLabel');if(label)label.textContent='موقع محدد ✓';closeModal();safe('تم حفظ موقع التوصيل ✅');}
  async function loadStores(){if(!window.supabaseClient||!map)return;const r=await window.supabaseClient.from('stores').select('id,name,category,address,latitude,longitude').eq('is_active',true);if(r.error||!r.data)return;storeMarkers.forEach(m=>m.remove());storeMarkers=r.data.filter(s=>Number.isFinite(+s.latitude)&&Number.isFinite(+s.longitude)).map(s=>new maplibregl.Marker({color:'#e11d2e'}).setLngLat([s.longitude,s.latitude]).setPopup(new maplibregl.Popup({offset:20}).setHTML(`<strong>${esc(s.name)}</strong><br><small>${esc(s.category||'')}</small>`)).addTo(map));}
  function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  window.openLocationPicker=openLocationPicker;
})();